spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  application:
    name: SURVEY-SERVICE

server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true