spring:
  application:
    name: SURVEY-SERVICE
  data:
    mongodb:
      #uri: mongodb+srv://root:root@surveykingcluster.vlvlu3o.mongodb.net/survey?retryWrites=true&w=majority
      database: survey
      host: localhost
      port: 27017
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true