Spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: surveydevs@gmail.com
    password: ycre opwc zmme hudn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: AUTHENTICATION-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true